//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// ????????
/// </summary>
public abstract partial class ActionEventBaseData: Bright.Config.BeanBase
{
    public ActionEventBaseData(ByteBuf _buf) 
    {
        PostInit();
    }

    public static ActionEventBaseData DeserializeActionEventBaseData(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case RangeDamageActionEventData.__ID__: return new RangeDamageActionEventData(_buf);
            case BulletActionEventData.__ID__: return new BulletActionEventData(_buf);
            case AddBuffActionEventData.__ID__: return new AddBuffActionEventData(_buf);
            case RemoveBuffActionEventData.__ID__: return new RemoveBuffActionEventData(_buf);
            case ChangeNumericActionEventData.__ID__: return new ChangeNumericActionEventData(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}