//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// battle buff effect base bean
/// </summary>
public abstract partial class BuffEffectBaseData: Bright.Config.BeanBase
{
    public BuffEffectBaseData(ByteBuf _buf) 
    {
        PostInit();
    }

    public static BuffEffectBaseData DeserializeBuffEffectBaseData(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case NoopBuffEffectData.__ID__: return new NoopBuffEffectData(_buf);
            case ChangeNumericBuffEffectData.__ID__: return new ChangeNumericBuffEffectData(_buf);
            case RelativeNumericBuffEffectData.__ID__: return new RelativeNumericBuffEffectData(_buf);
            case ActionEventBuffEffectData.__ID__: return new ActionEventBuffEffectData(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}