//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// change numeric buff modifier bean
/// </summary>
public sealed partial class ChangeNumericBuffModifierData:  BuffModifierBaseData 
{
    public ChangeNumericBuffModifierData(ByteBuf _buf)  : base(_buf) 
    {
        NumericType = _buf.ReadInt();
        Delta = _buf.ReadInt();
        PostInit();
    }

    public static ChangeNumericBuffModifierData DeserializeChangeNumericBuffModifierData(ByteBuf _buf)
    {
        return new ChangeNumericBuffModifierData(_buf);
    }

    /// <summary>
    /// numeric key to modify
    /// </summary>
    public int NumericType { get; private set; }
    /// <summary>
    /// delta per layer
    /// </summary>
    public int Delta { get; private set; }

    public const int __ID__ = 642422353;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "Delta:" + Delta + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}