//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// change numeric event bean
/// </summary>
public sealed partial class ChangeNumericActionEventData:  ActionEventBaseData 
{
    public ChangeNumericActionEventData(ByteBuf _buf)  : base(_buf) 
    {
        NumericType = _buf.ReadInt();
        Delta = _buf.ReadInt();
        TargetRule = _buf.ReadInt();
        InterruptLevel = _buf.ReadInt();
        PostInit();
    }

    public static ChangeNumericActionEventData DeserializeChangeNumericActionEventData(ByteBuf _buf)
    {
        return new ChangeNumericActionEventData(_buf);
    }

    /// <summary>
    /// numeric type
    /// </summary>
    public int NumericType { get; private set; }
    /// <summary>
    /// delta value
    /// </summary>
    public int Delta { get; private set; }
    /// <summary>
    /// target rule
    /// </summary>
    public int TargetRule { get; private set; }
    /// <summary>
    /// interrupt level
    /// </summary>
    public int InterruptLevel { get; private set; }

    public const int __ID__ = 997959921;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "Delta:" + Delta + ","
        + "TargetRule:" + TargetRule + ","
        + "InterruptLevel:" + InterruptLevel + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}