//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

public sealed partial class BuffConfig: Bright.Config.BeanBase
{
    public BuffConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        EffectData = BuffEffectBaseData.DeserializeBuffEffectBaseData(_buf);
        ModifierData = BuffModifierBaseData.DeserializeBuffModifierBaseData(_buf);
        Duration = _buf.ReadInt();
        TriggerInterval = _buf.ReadInt();
        MaxLayer = _buf.ReadInt();
        Goup = _buf.ReadInt();
        AddPolicy = (EBuffAddPolicy)_buf.ReadInt();
        SnapshotPolicy = (EBuffSnapshotPolicy)_buf.ReadInt();
        RemovePolicy = (EBuffRemovePolicy)_buf.ReadInt();
        TagGrantMask = _buf.ReadLong();
        TagBlockMask = _buf.ReadLong();
        CanDispel = _buf.ReadBool();
        KeepOnDeath = _buf.ReadBool();
        PeriodicStartDelayMs = _buf.ReadInt();
        PostInit();
    }

    public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
    {
        return new BuffConfig(_buf);
    }

    /// <summary>
    /// buffID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// name
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// desc
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// EffectData polymorphic bean
    /// </summary>
    public BuffEffectBaseData EffectData { get; private set; }
    /// <summary>
    /// ModifierData polymorphic bean
    /// </summary>
    public BuffModifierBaseData ModifierData { get; private set; }
    /// <summary>
    /// duration in ms
    /// </summary>
    public int Duration { get; private set; }
    /// <summary>
    /// trigger interval in ms
    /// </summary>
    public int TriggerInterval { get; private set; }
    /// <summary>
    /// max stack layer
    /// </summary>
    public int MaxLayer { get; private set; }
    /// <summary>
    /// group
    /// </summary>
    public int Goup { get; private set; }
    /// <summary>
    /// buff add policy
    /// </summary>
    public EBuffAddPolicy AddPolicy { get; private set; }
    /// <summary>
    /// buff snapshot policy
    /// </summary>
    public EBuffSnapshotPolicy SnapshotPolicy { get; private set; }
    /// <summary>
    /// buff remove policy
    /// </summary>
    public EBuffRemovePolicy RemovePolicy { get; private set; }
    /// <summary>
    /// granted combat tag mask
    /// </summary>
    public long TagGrantMask { get; private set; }
    /// <summary>
    /// blocked combat tag mask
    /// </summary>
    public long TagBlockMask { get; private set; }
    /// <summary>
    /// whether buff can be dispelled
    /// </summary>
    public bool CanDispel { get; private set; }
    /// <summary>
    /// whether buff keeps on death
    /// </summary>
    public bool KeepOnDeath { get; private set; }
    /// <summary>
    /// delay before first periodic trigger in ms
    /// </summary>
    public int PeriodicStartDelayMs { get; private set; }

    public const int __ID__ = -1370631787;
    public override int GetTypeId() => __ID__;

    public  void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        EffectData?.Resolve(_tables);
        ModifierData?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        EffectData?.TranslateText(translator);
        ModifierData?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "EffectData:" + EffectData + ","
        + "ModifierData:" + ModifierData + ","
        + "Duration:" + Duration + ","
        + "TriggerInterval:" + TriggerInterval + ","
        + "MaxLayer:" + MaxLayer + ","
        + "Goup:" + Goup + ","
        + "AddPolicy:" + AddPolicy + ","
        + "SnapshotPolicy:" + SnapshotPolicy + ","
        + "RemovePolicy:" + RemovePolicy + ","
        + "TagGrantMask:" + TagGrantMask + ","
        + "TagBlockMask:" + TagBlockMask + ","
        + "CanDispel:" + CanDispel + ","
        + "KeepOnDeath:" + KeepOnDeath + ","
        + "PeriodicStartDelayMs:" + PeriodicStartDelayMs + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}