//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;

namespace ET
{
   
[Config]
public partial class MonsterNumericConfigCategory: ConfigSingleton<MonsterNumericConfigCategory>
{
    private readonly Dictionary<int, MonsterNumericConfig> _dataMap;
    private readonly List<MonsterNumericConfig> _dataList;
    
    public MonsterNumericConfigCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, MonsterNumericConfig>();
        _dataList = new List<MonsterNumericConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MonsterNumericConfig _v;
            _v = MonsterNumericConfig.DeserializeMonsterNumericConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, MonsterNumericConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<MonsterNumericConfig> DataList => _dataList;

    public MonsterNumericConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterNumericConfig Get(int key) => _dataMap[key];
    public MonsterNumericConfig this[int key] => _dataMap[key];

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(MonsterNumericConfig).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}