//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

public sealed partial class PlayerNumericConfig: Bright.Config.BeanBase
{
    public PlayerNumericConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Speed = _buf.ReadFloat();
        PostInit();
    }

    public static PlayerNumericConfig DeserializePlayerNumericConfig(ByteBuf _buf)
    {
        return new PlayerNumericConfig(_buf);
    }

    /// <summary>
    /// 单位配置ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 生命值
    /// </summary>
    public int Hp { get; private set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public int Attack { get; private set; }
    /// <summary>
    /// 速度
    /// </summary>
    public float Speed { get; private set; }

    public const int __ID__ = -278520018;
    public override int GetTypeId() => __ID__;

    public  void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Hp:" + Hp + ","
        + "Attack:" + Attack + ","
        + "Speed:" + Speed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}