//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// range damage event bean
/// </summary>
public sealed partial class RangeDamageActionEventData:  ActionEventBaseData 
{
    public RangeDamageActionEventData(ByteBuf _buf)  : base(_buf) 
    {
        Radius = _buf.ReadInt();
        PostInit();
    }

    public static RangeDamageActionEventData DeserializeRangeDamageActionEventData(ByteBuf _buf)
    {
        return new RangeDamageActionEventData(_buf);
    }

    /// <summary>
    /// range radius in millimeters
    /// </summary>
    public int Radius { get; private set; }

    public const int __ID__ = -458226878;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Radius:" + Radius + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}