//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// shape based range damage event bean
/// </summary>
public sealed partial class ShapeRangeDamageActionEventData:  ActionEventBaseData 
{
    public ShapeRangeDamageActionEventData(ByteBuf _buf)  : base(_buf) 
    {
        ColliderType = (EColliderType)_buf.ReadInt();
        Radius = _buf.ReadInt();
        Width = _buf.ReadInt();
        Height = _buf.ReadInt();
        ForwardOffset = _buf.ReadInt();
        RightOffset = _buf.ReadInt();
        ExtraAngleDeg = _buf.ReadInt();
        PostInit();
    }

    public static ShapeRangeDamageActionEventData DeserializeShapeRangeDamageActionEventData(ByteBuf _buf)
    {
        return new ShapeRangeDamageActionEventData(_buf);
    }

    /// <summary>
    /// Circle or Box
    /// </summary>
    public EColliderType ColliderType { get; private set; }
    /// <summary>
    /// circle radius in millimeters
    /// </summary>
    public int Radius { get; private set; }
    /// <summary>
    /// box width in millimeters
    /// </summary>
    public int Width { get; private set; }
    /// <summary>
    /// box height in millimeters
    /// </summary>
    public int Height { get; private set; }
    /// <summary>
    /// forward offset in millimeters
    /// </summary>
    public int ForwardOffset { get; private set; }
    /// <summary>
    /// right offset in millimeters
    /// </summary>
    public int RightOffset { get; private set; }
    /// <summary>
    /// extra rotation in degrees
    /// </summary>
    public int ExtraAngleDeg { get; private set; }

    public const int __ID__ = -1845292157;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ColliderType:" + ColliderType + ","
        + "Radius:" + Radius + ","
        + "Width:" + Width + ","
        + "Height:" + Height + ","
        + "ForwardOffset:" + ForwardOffset + ","
        + "RightOffset:" + RightOffset + ","
        + "ExtraAngleDeg:" + ExtraAngleDeg + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}