//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// action event buff effect bean
/// </summary>
public sealed partial class ActionEventBuffEffectData:  BuffEffectBaseData 
{
    public ActionEventBuffEffectData(ByteBuf _buf)  : base(_buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);StartActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); StartActionEventIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TriggerActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerActionEventIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EndActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EndActionEventIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ExpireActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ExpireActionEventIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RemoveActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemoveActionEventIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DispelActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DispelActionEventIds.Add(_e0);}}
        PostInit();
    }

    public static ActionEventBuffEffectData DeserializeActionEventBuffEffectData(ByteBuf _buf)
    {
        return new ActionEventBuffEffectData(_buf);
    }

    /// <summary>
    /// action events when buff starts
    /// </summary>
    public System.Collections.Generic.List<int> StartActionEventIds { get; private set; }
    /// <summary>
    /// action events when buff triggers
    /// </summary>
    public System.Collections.Generic.List<int> TriggerActionEventIds { get; private set; }
    /// <summary>
    /// action events when buff ends
    /// </summary>
    public System.Collections.Generic.List<int> EndActionEventIds { get; private set; }
    /// <summary>
    /// action events when buff expires
    /// </summary>
    public System.Collections.Generic.List<int> ExpireActionEventIds { get; private set; }
    /// <summary>
    /// action events when buff is removed
    /// </summary>
    public System.Collections.Generic.List<int> RemoveActionEventIds { get; private set; }
    /// <summary>
    /// action events when buff is dispelled
    /// </summary>
    public System.Collections.Generic.List<int> DispelActionEventIds { get; private set; }

    public const int __ID__ = -849553262;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "StartActionEventIds:" + Bright.Common.StringUtil.CollectionToString(StartActionEventIds) + ","
        + "TriggerActionEventIds:" + Bright.Common.StringUtil.CollectionToString(TriggerActionEventIds) + ","
        + "EndActionEventIds:" + Bright.Common.StringUtil.CollectionToString(EndActionEventIds) + ","
        + "ExpireActionEventIds:" + Bright.Common.StringUtil.CollectionToString(ExpireActionEventIds) + ","
        + "RemoveActionEventIds:" + Bright.Common.StringUtil.CollectionToString(RemoveActionEventIds) + ","
        + "DispelActionEventIds:" + Bright.Common.StringUtil.CollectionToString(DispelActionEventIds) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}