//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// add buff event bean
/// </summary>
public sealed partial class AddBuffActionEventData:  ActionEventBaseData 
{
    public AddBuffActionEventData(ByteBuf _buf)  : base(_buf) 
    {
        BuffId = _buf.ReadInt();
        TargetRule = _buf.ReadInt();
        PostInit();
    }

    public static AddBuffActionEventData DeserializeAddBuffActionEventData(ByteBuf _buf)
    {
        return new AddBuffActionEventData(_buf);
    }

    /// <summary>
    /// buff config id
    /// </summary>
    public int BuffId { get; private set; }
    /// <summary>
    /// target rule
    /// </summary>
    public int TargetRule { get; private set; }

    public const int __ID__ = -737452870;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BuffId:" + BuffId + ","
        + "TargetRule:" + TargetRule + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}