//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// battle buff modifier base bean
/// </summary>
public abstract partial class BuffModifierBaseData: Bright.Config.BeanBase
{
    public BuffModifierBaseData(ByteBuf _buf) 
    {
        PostInit();
    }

    public static BuffModifierBaseData DeserializeBuffModifierBaseData(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case NoopBuffModifierData.__ID__: return new NoopBuffModifierData(_buf);
            case ChangeNumericBuffModifierData.__ID__: return new ChangeNumericBuffModifierData(_buf);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}