//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// projectile event bean
/// </summary>
public sealed partial class BulletActionEventData:  ActionEventBaseData 
{
    public BulletActionEventData(ByteBuf _buf)  : base(_buf) 
    {
        BulletConfigId = _buf.ReadInt();
        Speed = _buf.ReadInt();
        LifeMs = _buf.ReadInt();
        Radius = _buf.ReadInt();
        Count = _buf.ReadInt();
        SpreadAngleDeg = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);HitActionEventIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); HitActionEventIds.Add(_e0);}}
        PostInit();
    }

    public static BulletActionEventData DeserializeBulletActionEventData(ByteBuf _buf)
    {
        return new BulletActionEventData(_buf);
    }

    /// <summary>
    /// bullet config id
    /// </summary>
    public int BulletConfigId { get; private set; }
    /// <summary>
    /// speed in millimeters per second
    /// </summary>
    public int Speed { get; private set; }
    /// <summary>
    /// life time in milliseconds
    /// </summary>
    public int LifeMs { get; private set; }
    /// <summary>
    /// collision radius in millimeters
    /// </summary>
    public int Radius { get; private set; }
    /// <summary>
    /// projectile count
    /// </summary>
    public int Count { get; private set; }
    /// <summary>
    /// total spread angle in degrees
    /// </summary>
    public int SpreadAngleDeg { get; private set; }
    /// <summary>
    /// on hit action event ids
    /// </summary>
    public System.Collections.Generic.List<int> HitActionEventIds { get; private set; }

    public const int __ID__ = 1000928844;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "BulletConfigId:" + BulletConfigId + ","
        + "Speed:" + Speed + ","
        + "LifeMs:" + LifeMs + ","
        + "Radius:" + Radius + ","
        + "Count:" + Count + ","
        + "SpreadAngleDeg:" + SpreadAngleDeg + ","
        + "HitActionEventIds:" + Bright.Common.StringUtil.CollectionToString(HitActionEventIds) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}