//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

public sealed partial class MonsterSpawnConfig: Bright.Config.BeanBase
{
    public MonsterSpawnConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SceneName = _buf.ReadString();
        UnitConfigId = _buf.ReadInt();
        SpawnX = _buf.ReadInt();
        SpawnY = _buf.ReadInt();
        SpawnZ = _buf.ReadInt();
        Count = _buf.ReadInt();
        BehaviorTreeName = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SkillIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillIds[__index0] = __e0;}}
        OffsetX = _buf.ReadInt();
        OffsetY = _buf.ReadInt();
        OffsetZ = _buf.ReadInt();
        SpawnOnce = _buf.ReadBool();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Speed = _buf.ReadFloat();
        PostInit();
    }

    public static MonsterSpawnConfig DeserializeMonsterSpawnConfig(ByteBuf _buf)
    {
        return new MonsterSpawnConfig(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 场景名
    /// </summary>
    public string SceneName { get; private set; }
    /// <summary>
    /// 单位配置ID
    /// </summary>
    public int UnitConfigId { get; private set; }
    /// <summary>
    /// 出生点X
    /// </summary>
    public int SpawnX { get; private set; }
    /// <summary>
    /// 出生点Y
    /// </summary>
    public int SpawnY { get; private set; }
    /// <summary>
    /// 出生点Z
    /// </summary>
    public int SpawnZ { get; private set; }
    /// <summary>
    /// 数量
    /// </summary>
    public int Count { get; private set; }
    /// <summary>
    /// 行为树名
    /// </summary>
    public string BehaviorTreeName { get; private set; }
    /// <summary>
    /// 技能列表
    /// </summary>
    public int[] SkillIds { get; private set; }
    /// <summary>
    /// 每个怪X偏移
    /// </summary>
    public int OffsetX { get; private set; }
    /// <summary>
    /// 每个怪Y偏移
    /// </summary>
    public int OffsetY { get; private set; }
    /// <summary>
    /// 每个怪Z偏移
    /// </summary>
    public int OffsetZ { get; private set; }
    /// <summary>
    /// 是否只首刷一次
    /// </summary>
    public bool SpawnOnce { get; private set; }
    /// <summary>
    /// 生命值
    /// </summary>
    public int Hp { get; private set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public int Attack { get; private set; }
    /// <summary>
    /// 速度
    /// </summary>
    public float Speed { get; private set; }

    public const int __ID__ = 344337027;
    public override int GetTypeId() => __ID__;

    public  void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SceneName:" + SceneName + ","
        + "UnitConfigId:" + UnitConfigId + ","
        + "SpawnX:" + SpawnX + ","
        + "SpawnY:" + SpawnY + ","
        + "SpawnZ:" + SpawnZ + ","
        + "Count:" + Count + ","
        + "BehaviorTreeName:" + BehaviorTreeName + ","
        + "SkillIds:" + Bright.Common.StringUtil.CollectionToString(SkillIds) + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "OffsetZ:" + OffsetZ + ","
        + "SpawnOnce:" + SpawnOnce + ","
        + "Hp:" + Hp + ","
        + "Attack:" + Attack + ","
        + "Speed:" + Speed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}