//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// empty buff modifier bean
/// </summary>
public sealed partial class NoopBuffModifierData:  BuffModifierBaseData 
{
    public NoopBuffModifierData(ByteBuf _buf)  : base(_buf) 
    {
        PostInit();
    }

    public static NoopBuffModifierData DeserializeNoopBuffModifierData(ByteBuf _buf)
    {
        return new NoopBuffModifierData(_buf);
    }


    public const int __ID__ = 1786250934;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}