//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

/// <summary>
/// relative numeric buff effect bean
/// </summary>
public sealed partial class RelativeNumericBuffEffectData:  BuffEffectBaseData 
{
    public RelativeNumericBuffEffectData(ByteBuf _buf)  : base(_buf) 
    {
        NumericType = _buf.ReadInt();
        BaseNumericType = _buf.ReadInt();
        Ratio = _buf.ReadInt();
        InterruptLevel = _buf.ReadInt();
        PostInit();
    }

    public static RelativeNumericBuffEffectData DeserializeRelativeNumericBuffEffectData(ByteBuf _buf)
    {
        return new RelativeNumericBuffEffectData(_buf);
    }

    /// <summary>
    /// target numeric type
    /// </summary>
    public int NumericType { get; private set; }
    /// <summary>
    /// base numeric type
    /// </summary>
    public int BaseNumericType { get; private set; }
    /// <summary>
    /// ratio in ten-thousandths
    /// </summary>
    public int Ratio { get; private set; }
    /// <summary>
    /// interrupt level
    /// </summary>
    public int InterruptLevel { get; private set; }

    public const int __ID__ = 684054127;
    public override int GetTypeId() => __ID__;

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "NumericType:" + NumericType + ","
        + "BaseNumericType:" + BaseNumericType + ","
        + "Ratio:" + Ratio + ","
        + "InterruptLevel:" + InterruptLevel + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}